### ISSUE TITLE
게시판 CRUD 기능

### ISSUE THREAD

**Issue by bjho606** [ssafy-pjt-naem/naem-back#42]
### 📄 Describe

관리자를 위한 기능으로, 현재 default로 존재하는 ("전체", "인기", "자유", "보호자", "취업", "재활 치료", "복지 혜택") 게시판들 외에 추가적으로 CRUD를 할 수 있는 기능을 개발합니다.

### ✅ Tasks

- [x] 게시판의 CRUD 기능 추가
   - [x] 게시판 생성
   - [x] 모든 (삭제되지 않은) 게시판 목록 불러오기
   - [x] 활성화된 게시판 목록 불러오기
   - [x] 게시판 숨김
   - [x] 게시판 삭제 (soft delete)
- [x] 각 기능들에 대한 테스트코드 작성
- [ ] api 명세서 작성

### 🙋🏻 More

하나둘셋 화이팅!
